### ISSUE TITLE
Cant install ?

### ISSUE THREAD

**Issue by AlexanderLindkjaer** [simonridley/tracking-code-manager#2]
Hi @simonridley 🙂  Thanks for the free addon ! 

In statamic `3.0.26` hitting install doesn't really do anything? manually composer require does not seem to activate the addon either. Am I missing something?

![Skærmbillede 2020-11-11 kl  11 19 03](https://user-images.githubusercontent.com/33224052/98799752-cef1e200-240f-11eb-9878-5c710d109757.png)

**Comment by simonridley** [comment]
Hi @AlexanderLindkjaer I just created a fresh Statamic install on 3.0.26 and installed the add-on by going to Addons > find the addon > Install

This installed the addon and the menu item appears in the bottom the left nav, below Utilities as expected

Can you check if that nav item appeared? See screenshot

![image](https://user-images.githubusercontent.com/5379986/98801215-6ef83d00-2409-11eb-90ce-b27eb1ab1a0a.png)

**Comment by AlexanderLindkjaer** [comment]
Got it working, I had some write permission issues on my local installation. Thank you for the quick reply and sorry for the inconvenience. 

Have a nice day 🙂
