### ISSUE TITLE
Segmentation fault in Statamic 4

### ISSUE THREAD

**Issue by benfreke** [simonridley/tracking-code-manager#5]
Hi

I managed to track this down to this plugin, but I wasn't able to find out why. 

In /src/http/ServiceProvider.php, line 21. Comment out the `Nav::extend` call and the segmentation fault disappears. 

This was working in Statamic 3, so perhaps there have been some changes to how to register an addon or a route. 

I did look through the documentation but nothing jumped out at me as wrong about the ServiceProvider. The icon for the menu item doesn't display. 

And to make this even harder to track down, everything works (except the image displaying) when xdebug is run. 

This is all happening in Linux via WSL2, so it might also just end up being a permissions problem (I'm running in Docker) if it works fine on other machines. If so, then I can try some other things to track this one done properly.

Ben

**Comment by hhhc** [comment]
Just updated to Statamic 4 and I have a similar issue: Target class [TrackingCodeManagerController] does not exist.

Reinstalling the plugin did not help, deleted all vendor dir did not help, really clueless.

**Comment by simonridley** [comment]
I'll have a look, also open to PRs!

**Comment by hhhc** [comment]
Just committed a PR

**Comment by benfreke** [comment]
Can confirm that PR #6  works. It'd be great to get a new version out to support this please.

**Comment by simonridley** [comment]
Thanks @hhhc and @benfreke I've merged that PR and tagged as 1.0.1
